feat: setup min value that can be transferred
worldwide-asset-exchange/deposit-screen pull request #1
Opened 2022-06-14 13:39 UTC by manh-vv

2022-06-14 15:39 UTC, manh-vv reviewed
Ready for reviewing.

2022-06-21 23:51 UTC, porkchop requested changes
Looking good @manh-vv I see only one issue to fix up

2022-06-21 23:51 UTC, porkchop commented on src/deposit_screen.cpp
> +   auto gstate = _global.get();
@manh-vv I think we might want to make some minimum verifications here as well:
```
    check(get_first_receiver() == "eosio.token"_n, "Invalid token contract");

    if (from == get_self() || to != get_self()) {
      return;
    }

    check(quantity.symbol == WAX_SYMBOL, "Invalid token");
```

2022-06-22 02:00 UTC, manh-vv commented on src/deposit_screen.cpp
> +   auto gstate = _global.get();
Thank @porkchop .
I applied your comment.

2022-06-22 02:01 UTC, manh-vv reviewed
applied comment

2022-06-22 02:13 UTC, porkchop approved these changes
LGTM Thanks @manh-vv

2022-06-22 02:13 UTC, merged